spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          client-id: "1066405163833-lnhm75paledsl08dqfduk3rvqofnii0m.apps.googleusercontent.com"
          client-secret: "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"
          introspection-uri: https://www.googleapis.com
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/pos-app-postgres
    username: changanuong1742
    password: chanvkl205
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: riumeoren2@gmail.com
    password: kserqamxuituavbg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 9898

minio:
  url: http://localhost:9000/
  accessKey: EfkJnF3emHOstb45ErWk
  secretKey: Q6menNGqUIpXpfnoUVaqDKd9gXasOmiNd4KMia9s
  bucketName: pos-app

url-frontend-guest: http://localhost:4200/
url-frontend-backend: http://localhost:54262/